name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.PRIVATE_KEY}}
            SSH_HOST: ${{ secrets.HOST }}
      - name: SSH deploy  $GITHUB_REF branch version
        run: |
              echo ${GITHUB_REF##*/}
              echo "GITHUB_REF=${GITHUB_REF##*/}" > sshenv
              scp sshenv staging:~/.ssh/environment
              LC_parameter="${GITHUB_REF##*/}" ssh -o SendEnv=LC_parameter staging 'cd liv && ls && rm -r dist && git fetch && sudo apt-get install nodejs && node --version && npm rebuild node-sass && git checkout $LC_parameter && git pull && npm install && npm run build'
